# Site settings
title: Paulo BF Almeida
description: Portifólio do Paulo
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: https://paulobfalmeida.github.io # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Paulo B F Almeida
user_title: Game Developer
user_description: Sobre mim.
email: paulobfalmeida@gmail.com
github_username:  paulobfalmeida
# twitter_username:
# gplus_username:

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
