# Site settings
title: Paulo BF Almeida
description: Portifólio do Paulo
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: https://paulobfalmeida.github.io # the base hostname & protocol for your site

# --- User settings ---
username: Paulo B F Almeida
user_title: Game Designer
email: paulobfalmeida@gmail.com
github_username: paulobfalmeida
github_link: https://github.com/paulobfalmeida
itch_username: paulobfalmeida
itch_link: https://paulobfalmeida.itch.io/
cv_link: http://lattes.cnpq.br/8271715880695926

lang: en
languages: ["en", "pt"]

# --- Projects settings ---
# maximum amount of projects to display on home page
display_max_personal: 4
display_max_professional: 3

collections:
  projects_personal:
    output: true
  projects_professional:
    output: true

# --- Colors ---
color_btn_hover: '#394b60'
# #54516a
# #1a222c

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

plugins:
  - jekyll-seo-tag
